
export const LOAD_ALL_NEWS_REQUEST = 'LOAD_ALL_NEWS_REQUEST'
export const LOAD_ALL_NEWS_SUCCESS = 'LOAD_ALL_NEWS_SUCCESS'
export const LOAD_ALL_NEWS_ERROR = 'LOAD_ALL_NEWS_ERROR'

export const USER_SIGN_IN = 'USER_SIGN_IN'
export const USER_LOGOUT = 'USER_LOGOUT'